server:
  port: 9977
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.23.109.20:3306/jpa_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: Aa@111111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
