server:
  port: 8781
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#服务的名称
spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000

#自定义负载均衡策略
product-service: #输入服务名  对他的端口进行随机访问 而不是轮询访问
  ribbon:  #order自己是ribbon所以才用   product不是ribbon所以product没有这条
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#修改调用超时时间
feign:
  #开启启用hystrix  默认是关闭的
  hystrix:
  enabled: true#开启hystrix
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 1000

#把hystrix超时时间禁用
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false

#execution.isolation.thread.timeoutInMilliseconds=4000

#设置超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
